---
title: "inequality"
author: "alicia"
date: "11/16/2021"
output: html_document
---

```{r setup, eval=FALSE}
#snapshot
#renv::snapshot

#install the same package
#renv::restore()
```

## R Markdown
data 
https://hub.arcgis.com/datasets/esri::world-countries-generalized/about
http://hdr.undp.org/en/indicators/68606#
#load package
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(countrycode)
```

#load data

```{r}
HDI <- read_csv(here::here("data","Gender Inequality Index (GII).csv"),
                      locale = locale(encoding="latin1"),
                      na = "..",skip = 5)
World <- st_read(here::here("data","World_Countries__Generalized_.shp"))

```
#column names
select colunms we want and change the country name to code, using 'countrycode'
```{r}
HDIcols <- HDI %>%
  clean_names()%>%
  select(country,x2019,x2010)%>%
  mutate(difference=x2019-x2010)%>%
  slice(1:189,)%>%
  mutate(iso_code=countrycode(HDIcols$country,origin = 'country.name',destination = 'iso2c'))
```
##join
```{r}
Join_HDI <- World %>%
  clean_names()%>%
  left_join(.,
            HDIcols,
            by = c("aff_iso"="iso_code"))
```

